spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/healthcare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: examly
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
