spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmts
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: examly
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
